.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "SNYK\-AUTH" "1" "July 2021" "Snyk.io"
.SH "NAME"
\fBsnyk\-auth\fR \- Authenticate Snyk CLI with a Snyk account
.SH "SYNOPSIS"
\fBsnyk\fR \fBauth\fR [\fIAPI_TOKEN\fR] [\fIOPTIONS\fR]
.SH "DESCRIPTION"
Authenticate Snyk CLI with a Snyk account\. Running \fB$ snyk auth\fR without an \fIAPI_TOKEN\fR will open a browser window and asks you to login with Snyk account and authorize\. When inputting an \fIAPI_TOKEN\fR, it will be validated with Snyk API\.
.P
When running in a CI environment \fIAPI_TOKEN\fR is required\.
.SH "OPTIONS"
.TP
[\fIAPI_TOKEN\fR]
Your Snyk token\. May be an user token or a service account\.
.br
How to get your account token \fIhttps://snyk\.co/ucT6J\fR
.br
How to use Service Accounts \fIhttps://snyk\.co/ucT6L\fR
.br

.SS "Flags available accross all commands"
.TP
\fB\-\-insecure\fR
Ignore unknown certificate authorities\.
.TP
\fB\-d\fR
Output debug logs\.
.TP
\fB\-\-quiet\fR, \fB\-q\fR
Silence all output\.
.TP
\fB\-\-version\fR, \fB\-v\fR
Prints versions\.
.TP
[\fICOMMAND\fR] \fB\-\-help\fR, \fB\-\-help\fR [\fICOMMAND\fR], \fB\-h\fR
Prints a help text\. You may specify a \fICOMMAND\fR to get more details\.
.SH "EXIT CODES"
Possible exit codes and their meaning:
.P
\fB0\fR: success, no vulns found
.br
\fB1\fR: action_needed, vulns found
.br
\fB2\fR: failure, try to re\-run command
.br
\fB3\fR: failure, no supported projects detected
.br
.SH "ENVIRONMENT"
You can set these environment variables to change CLI run settings\.
.TP
\fBSNYK_TOKEN\fR
Snyk authorization token\. Setting this envvar will override the token that may be available in your \fBsnyk config\fR settings\.
.IP
How to get your account token \fIhttps://snyk\.co/ucT6J\fR
.br
How to use Service Accounts \fIhttps://snyk\.co/ucT6L\fR
.br

.TP
\fBSNYK_CFG_KEY\fR
Allows you to override any key that\'s also available as \fBsnyk config\fR option\.
.IP
E\.g\. \fBSNYK_CFG_ORG\fR=myorg will override default org option in \fBconfig\fR with "myorg"\.
.TP
\fBSNYK_REGISTRY_USERNAME\fR
Specify a username to use when connecting to a container registry\. Note that using the \fB\-\-username\fR flag will override this value\. This will be ignored in favour of local Docker binary credentials when Docker is present\.
.TP
\fBSNYK_REGISTRY_PASSWORD\fR
Specify a password to use when connecting to a container registry\. Note that using the \fB\-\-password\fR flag will override this value\. This will be ignored in favour of local Docker binary credentials when Docker is present\.
.SH "Connecting to Snyk API"
By default Snyk CLI will connect to \fBhttps://snyk\.io/api/v1\fR\.
.TP
\fBSNYK_API\fR
Sets API host to use for Snyk requests\. Useful for on\-premise instances and configuring proxies\. If set with \fBhttp\fR protocol CLI will upgrade the requests to \fBhttps\fR\. Unless \fBSNYK_HTTP_PROTOCOL_UPGRADE\fR is set to \fB0\fR\.
.TP
\fBSNYK_HTTP_PROTOCOL_UPGRADE\fR=0
If set to the value of \fB0\fR, API requests aimed at \fBhttp\fR URLs will not be upgraded to \fBhttps\fR\. If not set, the default behavior will be to upgrade these requests from \fBhttp\fR to \fBhttps\fR\. Useful e\.g\., for reverse proxies\.
.TP
\fBHTTPS_PROXY\fR and \fBHTTP_PROXY\fR
Allows you to specify a proxy to use for \fBhttps\fR and \fBhttp\fR calls\. The \fBhttps\fR in the \fBHTTPS_PROXY\fR means that \fIrequests using \fBhttps\fR protocol\fR will use this proxy\. The proxy itself doesn\'t need to use \fBhttps\fR\.
.SH "NOTICES"
.SS "Snyk API usage policy"
The use of Snyk\'s API, whether through the use of the \'snyk\' npm package or otherwise, is subject to the terms & conditions \fIhttps://snyk\.co/ucT6N\fR
