//go:build ignore

// Command gen regenerates owners_gen.go from the catalog-info.yaml files that
// the CLI's dependency modules ship at their module root.
//
// It enumerates every module in the build list via `go list -m -json all`,
// reads catalog-info.yaml from each module's directory (present in the Go
// module cache), extracts the Backstage ownership fields, and writes the result
// as a generated Go source file that populates internal_workflows.moduleOwners.
//
// The generated file is intentionally not checked in; run this before building
// preview binaries:
//
//	go generate ./internal/internal_workflows/...
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"

	"gopkg.in/yaml.v3"
)

const (
	modulePrefix = "github.com/snyk/"
	outputFile   = "owners_gen.go"
)

// module mirrors the relevant fields of `go list -m -json` output.
type module struct {
	Path string
	Dir  string
	Main bool
}

// catalog mirrors the relevant fields of a Backstage catalog-info.yaml.
type catalog struct {
	Metadata struct {
		Name        string            `yaml:"name"`
		Annotations map[string]string `yaml:"annotations"`
	} `yaml:"metadata"`
	Spec struct {
		Type  string `yaml:"type"`
		Owner string `yaml:"owner"`
	} `yaml:"spec"`
}

type owner struct {
	Module      string
	Component   string
	Type        string
	Owner       string
	TeamSlug    string
	ProjectSlug string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "internal_workflows/gen:", err)
		os.Exit(1)
	}
}

func run() error {
	mods, err := listModules()
	if err != nil {
		return err
	}

	var owners []owner
	for _, m := range mods {
		if m.Main || m.Dir == "" || len(m.Path) < len(modulePrefix) || m.Path[:len(modulePrefix)] != modulePrefix {
			continue
		}
		path := filepath.Join(m.Dir, "catalog-info.yaml")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("reading %s: %w", path, err)
		}
		var c catalog
		if err := yaml.Unmarshal(data, &c); err != nil {
			return fmt.Errorf("parsing %s: %w", path, err)
		}
		owners = append(owners, owner{
			Module:      m.Path,
			Component:   c.Metadata.Name,
			Type:        c.Spec.Type,
			Owner:       c.Spec.Owner,
			TeamSlug:    c.Metadata.Annotations["github.com/team-slug"],
			ProjectSlug: c.Metadata.Annotations["github.com/project-slug"],
		})
	}

	sort.Slice(owners, func(i, j int) bool { return owners[i].Module < owners[j].Module })

	return writeOutput(owners)
}

func listModules() ([]module, error) {
	cmd := exec.Command("go", "list", "-m", "-json", "all")
	// The module graph to enumerate can differ between a public and a private
	// build. SNYK_EXTOWNER_MODULE_DIR lets the build point `go list` at the
	// module actually being built (e.g. cliv2-private) so private-only
	// extensions are included; it defaults to this package's own module.
	if dir := os.Getenv("SNYK_EXTOWNER_MODULE_DIR"); dir != "" {
		cmd.Dir = dir
	}
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list -m -json all: %w", err)
	}
	var mods []module
	dec := json.NewDecoder(bytes.NewReader(out))
	for dec.More() {
		var m module
		if err := dec.Decode(&m); err != nil {
			return nil, fmt.Errorf("decoding go list output: %w", err)
		}
		mods = append(mods, m)
	}
	return mods, nil
}

func writeOutput(owners []owner) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen.go; DO NOT EDIT.\n")
	buf.WriteString("// Regenerate with: go generate ./internal/internal_workflows/...\n\n")
	buf.WriteString("package internal_workflows\n\n")
	buf.WriteString("// Populates moduleOwners with the build-time snapshot of module ownership,\n")
	buf.WriteString("// extracted from each module's catalog-info.yaml.\n")
	buf.WriteString("func init() {\n")
	buf.WriteString("\tmoduleOwners = []Owner{\n")
	for _, o := range owners {
		fmt.Fprintf(&buf, "\t\t{Module: %s, Component: %s, Type: %s, Owner: %s, TeamSlug: %s, ProjectSlug: %s},\n",
			strconv.Quote(o.Module), strconv.Quote(o.Component), strconv.Quote(o.Type),
			strconv.Quote(o.Owner), strconv.Quote(o.TeamSlug), strconv.Quote(o.ProjectSlug))
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outputFile, err)
	}
	fmt.Printf("internal_workflows/gen: wrote %d owners to %s\n", len(owners), outputFile)
	return nil
}
