FROM alpine:3 AS BUILDER

ARG CLI_DOWNLOAD_BASE_URL
ARG SNYK_VERSION

RUN apk --no-cache add curl ca-certificates
RUN curl --compressed -sL \
    "${CLI_DOWNLOAD_BASE_URL}cli/v${SNYK_VERSION}/snyk-linux" \
    -o /usr/local/bin/snyk \
    && chmod +x /usr/local/bin/snyk

RUN curl -sL \
    https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox \
    -o /usr/local/bin/busybox \
    && chmod +x /usr/local/bin/busybox

FROM scratch
COPY --from=BUILDER /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=BUILDER /usr/local/bin/busybox /bin/busybox
COPY --from=BUILDER /usr/local/bin/snyk /usr/local/bin/snyk
ENV PATH="/usr/local/bin:/bin"
ENTRYPOINT ["/bin/busybox", "sh"]
