FROM node:8-slim

MAINTAINER Snyk Ltd

RUN apt-get update && apt-get install -y git build-essential zlib1g-dev libssl-dev jq
RUN chmod -R a+wrx /home/node
WORKDIR /home/node
ENV HOME /home/node

# Install pyenv
RUN curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
ENV PATH "/home/node/.pyenv/bin:$PATH"
RUN eval "$(pyenv init -)"
RUN eval "$(pyenv virtualenv-init -)"

# Install python versions
RUN pyenv install 3.6.7
RUN pyenv install 3.5.6
RUN pyenv install 3.4.9
RUN pyenv install 2.7.15
RUN pyenv global 3.6.7 3.5.6 3.4.9 2.7.15  
ENV PATH "/home/node/.pyenv/shims:$PATH"
RUN pip install virtualenv pipenv

# Install snyk cli
RUN npm install --global snyk snyk-to-html

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

ADD docker-python-entrypoint.sh .
ADD docker-entrypoint.sh .
ADD snyk_report.css .

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENTRYPOINT ["./docker-python-entrypoint.sh"]

# Default command is `snyk test`
# Override with `docker run ... snyk/snyk-cli <command> <args>`
CMD ["test"]

