FROM python:2.7-slim

MAINTAINER Snyk Ltd

RUN mkdir /home/node
WORKDIR /home/node

# Install Python utilities, node, Snyk CLI
RUN pip install pip pipenv virtualenv -U && \
    apt-get update && \
    apt-get install -y build-essential curl git && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    npm install --global snyk && \
    apt-get autoremove -y && \
    apt-get clean && \
    chmod -R a+wrx /home/node

ENV HOME /home/node

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

COPY docker-python-entrypoint.sh .
COPY docker-entrypoint.sh .

ENV SNYK_INTEGRATION_NAME DOCKER_SNYK_CLI
ENV SNYK_INTEGRATION_VERSION python-2

ENTRYPOINT ["./docker-python-entrypoint.sh"]

# Default command is `snyk test`
# Override with `docker run ... snyk/snyk-cli <command> <args>`
CMD ["test"]
