FROM openjdk:11-jdk-slim-buster

MAINTAINER Snyk Ltd

RUN mkdir /home/node
WORKDIR /home/node

# Install maven, node, cli
RUN apt-get update && \
  apt-get install -y curl git && \
  curl -L -o apache-maven-3.6.3-bin.tar.gz https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz && \
  tar -xvzf apache-maven-3.6.3-bin.tar.gz && \
  rm -f apache-maven-3.6.3-bin.tar.gz && \
  curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
  apt-get install -y nodejs && \
  npm install --global snyk snyk-to-html && \
  apt-get autoremove -y && \
  apt-get clean && \
  chmod -R a+wrx /home/node

ENV HOME /home/node
ENV M2 /home/node/.m2
ENV PATH /home/node/apache-maven-3.6.3/bin:$PATH

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

ADD docker-entrypoint.sh .

ENV SNYK_INTEGRATION_NAME DOCKER_SNYK_CLI
ENV SNYK_INTEGRATION_VERSION maven-3.6.3_java11

ENTRYPOINT ["./docker-entrypoint.sh"]

# Default command is `snyk test`
# Override with `docker run ... snyk/snyk-cli <command> <args>`
CMD ["test"]
