FROM golang:1.18-bullseye

LABEL maintainer="Snyk Ltd"

RUN mkdir /home/node
WORKDIR /home/node

# Install snyk cli and clean up
RUN apt-get update && \
    apt-get install -y build-essential curl git && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    npm install --global snyk snyk-to-html && \
    apt-get autoremove -y && \
    apt-get clean && \
    chmod -R a+wrx /home/node

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

COPY docker-entrypoint.sh .

ENV SNYK_INTEGRATION_NAME DOCKER_SNYK_CLI

ENV SNYK_INTEGRATION_VERSION go-1.8

ENTRYPOINT ["./docker-entrypoint.sh"]

# Default command is `snyk test`
# Override with `docker run ... snyk/snyk-cli <command> <args>`
CMD ["test"]