FROM openjdk:8-jdk-slim

MAINTAINER Snyk Ltd

RUN mkdir /home/node
WORKDIR /home/node

# Install sbt, node, cli
RUN apt-get update && \
    apt-get install -y curl apt-transport-https git && \
    curl -L -o sbt-0.13.16.deb https://dl.bintray.com/sbt/debian/sbt-0.13.16.deb && \
    dpkg -i sbt-0.13.16.deb && \
    rm sbt-0.13.16.deb && \
    apt-get update && \
    apt-get install -y sbt && \
    sbt sbtVersion && \
    echo "docker-user ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers  && \
    mkdir -p /root/.sbt/0.13/plugins  && \
    mkdir -p /home/node/.sbt/0.13/plugins  && \
    echo "addSbtPlugin(\"net.virtual-void\" % \"sbt-dependency-graph\" % \"0.8.2\")" >> /root/.sbt/0.13/plugins/build.sbt && \
    echo "addSbtPlugin(\"net.virtual-void\" % \"sbt-dependency-graph\" % \"0.8.2\")" >> /home/node/.sbt/0.13/plugins/build.sbt && \
    echo "net.virtualvoid.sbt.graph.DependencyGraphSettings.graphSettings" >> /root/.sbt/0.13/user.sbt && \
    echo "net.virtualvoid.sbt.graph.DependencyGraphSettings.graphSettings" >> /home/node/.sbt/0.13/user.sbt && \
    echo "-sbt-version  0.13.16" >> /etc/sbt/sbtopts && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    npm install --global snyk snyk-to-html && \
    apt-get autoremove -y && \
    apt-get clean && \
    chmod -R a+wrx /home/node

ENV HOME /home/node
ENV M2 /home/node/.m2

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

COPY docker-entrypoint.sh .

ENV SNYK_INTEGRATION_NAME DOCKER_SNYK_CLI
ENV SNYK_INTEGRATION_VERSION sbt-0.13.16

ENTRYPOINT ["./docker-entrypoint.sh"]

# Default command is `snyk test`
# Override with `docker run ... snyk/snyk-cli <command> <args>`
CMD ["test"]
