FROM node:8-slim

MAINTAINER Snyk Ltd

WORKDIR /home/node
ENV HOME /home/node

# Install python, virtualenv and cli
RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-pip libssl-dev jq && \
    pip3 install pip pipenv virtualenv -U && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip && \
    npm install --global snyk snyk-to-html && \
    apt-get autoremove -y && \
    apt-get clean && \
    chmod -R a+wrx /home/node

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

COPY docker-python-entrypoint.sh .
COPY docker-entrypoint.sh .
COPY snyk_report.css .

ENTRYPOINT ["./docker-python-entrypoint.sh"]

# Default command is `snyk test`
# Override with `docker run ... snyk/snyk-cli <command> <args>`
CMD ["test"]

