FROM node:gallium-buster-slim

MAINTAINER Snyk Ltd

WORKDIR /home/node
ENV HOME /home/node

# Install snyk cli and clean up
RUN apt-get update && \
    apt-get install -y git && \
    npm install --global snyk snyk-to-html && \
    apt-get autoremove -y && \
    apt-get clean && \
    chmod -R a+wrx /home/node

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

COPY docker-entrypoint.sh .

ENV SNYK_INTEGRATION_NAME DOCKER_SNYK_CLI
# This image is currently being used for nuget, composer and ruby
# If we see a tons of usage, we can split the analytics
ENV SNYK_INTEGRATION_VERSION npm

ENTRYPOINT ["./docker-entrypoint.sh"]

# Default command is `snyk test`
# Override with `docker run ... snyk/snyk-cli <command> <args>`
CMD ["test"]
