// Package legacyschema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package legacyschema

// Defines values for NodeInfoLabelPruned.
const (
	Cyclic NodeInfoLabelPruned = "cyclic"
	True   NodeInfoLabelPruned = "true"
)

// Defines values for NodeInfoLabelScope.
const (
	Dev  NodeInfoLabelScope = "dev"
	Prod NodeInfoLabelScope = "prod"
)

// DepGraphData defines model for DepGraphData.
type DepGraphData struct {
	Graph *struct {
		Nodes      *[]GraphNode `json:"nodes,omitempty"`
		RootNodeId *string      `json:"rootNodeId,omitempty"`
	} `json:"graph,omitempty"`
	PkgManager *PkgManager `json:"pkgManager,omitempty"`
	Pkgs       *[]struct {
		Id   *string  `json:"id,omitempty"`
		Info *PkgInfo `json:"info,omitempty"`
	} `json:"pkgs,omitempty"`
	SchemaVersion *string `json:"schemaVersion,omitempty"`
}

// GraphNode defines model for GraphNode.
type GraphNode struct {
	Deps *[]struct {
		NodeId *string `json:"nodeId,omitempty"`
	} `json:"deps,omitempty"`
	Info   *NodeInfo `json:"info,omitempty"`
	NodeId *string   `json:"nodeId,omitempty"`
	PkgId  *string   `json:"pkgId,omitempty"`
}

// Node defines model for Node.
type Node struct {
	Info *NodeInfo `json:"info,omitempty"`
}

// NodeInfo defines model for NodeInfo.
type NodeInfo struct {
	Labels            *map[string]NodeInfoLabel `json:"labels,omitempty"`
	VersionProvenance *VersionProvenance        `json:"versionProvenance,omitempty"`
}

// NodeInfoLabel defines model for NodeInfoLabel.
type NodeInfoLabel struct {
	Pruned *NodeInfoLabelPruned `json:"pruned,omitempty"`
	Scope  *NodeInfoLabelScope  `json:"scope,omitempty"`
	Type   *string              `json:"type,omitempty"`
}

// NodeInfoLabelPruned defines model for NodeInfoLabel.Pruned.
type NodeInfoLabelPruned string

// NodeInfoLabelScope defines model for NodeInfoLabel.Scope.
type NodeInfoLabelScope string

// Pkg defines model for Pkg.
type Pkg struct {
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version"`
}

// PkgInfo defines model for PkgInfo.
type PkgInfo struct {
	Name    *string `json:"name,omitempty"`
	Purl    *string `json:"purl"`
	Version *string `json:"version"`
}

// PkgManager defines model for PkgManager.
type PkgManager struct {
	Name         *string `json:"name,omitempty"`
	Repositories *[]struct {
		Alias *string `json:"alias,omitempty"`
	} `json:"repositories,omitempty"`
	Version *string `json:"version"`
}

// VersionProvenance defines model for VersionProvenance.
type VersionProvenance struct {
	Location *string `json:"location,omitempty"`
	Property *struct {
		Name *string `json:"name,omitempty"`
	} `json:"property"`
	Type *string `json:"type,omitempty"`
}
