#!/usr/bin/env bash
set -e

mkdir binary-releases

# adds a file to identify a build as a standalone binary
echo '' > dist/STANDALONE

npx pkg . -t node14-alpine-x64 -o binary-releases/snyk-alpine
npx pkg . -t node12-linux-x64 -o binary-releases/snyk-linux
npx pkg . -t node12-macos-x64 -o binary-releases/snyk-macos
npx pkg . -t node12-win-x64 -o binary-releases/snyk-win-unsigned.exe

# build docker package
./release-scripts/docker-desktop-release.sh

# sign the windows binary
./release-scripts/sign-windows-binary.sh

# compute checksums
shasum -a 256 binary-releases/snyk-alpine > binary-releases/snyk-alpine.sha256
shasum -a 256 binary-releases/snyk-linux > binary-releases/snyk-linux.sha256
shasum -a 256 binary-releases/snyk-macos > binary-releases/snyk-macos.sha256
# note: checksum for snyk-win.exe is generated by `sign-windows-binary.sh`
# note: checksum for docker-mac-signed-bundle is generated by `docker-desktop-release.sh`

# removes the file we use to identify a build as a standalone binary
rm dist/STANDALONE

ls -la
