#!/usr/bin/env bash
set -e

mkdir binary-releases

npx pkg . --compress Brotli -t node14-alpine-x64 -o binary-releases/snyk-alpine
npx pkg . --compress Brotli -t node14-linux-x64  -o binary-releases/snyk-linux
npx pkg . --compress Brotli -t node14-macos-x64  -o binary-releases/snyk-macos
npx pkg . --compress Brotli -t node14-win-x64    -o binary-releases/snyk-win-unsigned.exe

npx pkg . --compress Brotli -t node14-alpine-arm64 -o binary-releases/snyk-alpine-arm64
npx pkg . --compress Brotli -t node14-linux-arm64  -o binary-releases/snyk-linux-arm64
npx pkg . --compress Brotli -t node14-macos-arm64  -o binary-releases/snyk-darwin-arm64

# build docker package
./release-scripts/docker-desktop-release.sh
./release-scripts/docker-desktop-release-arm64.sh

# sign the windows binary
./release-scripts/sign-windows-binary.sh

# compute checksums
pushd binary-releases
shasum -a 256 snyk-alpine >snyk-alpine.sha256
shasum -a 256 snyk-linux >snyk-linux.sha256
shasum -a 256 snyk-macos >snyk-macos.sha256
shasum -a 256 snyk-alpine-arm64 >snyk-alpine-arm64.sha256
shasum -a 256 snyk-linux-arm64 >snyk-linux-arm64.sha256
shasum -a 256 snyk-macos-arm64 >snyk-macos-arm64.sha256
# note: checksum for snyk-win.exe is generated by `sign-windows-binary.sh`
# note: checksum for docker-mac-signed-bundle is generated by `docker-desktop-release.sh`
popd

ls -la
