#!/usr/bin/env bash
set -euo pipefail

# Do not run this file locally. To build release artifacts, see CONTRIBUTING.

make prepack

make binary-releases/snyk-fix.tgz
make binary-releases/snyk-protect.tgz
make binary-releases/snyk.tgz

make binary-releases/snyk-alpine
make binary-releases/snyk-linux
make binary-releases/snyk-macos
make binary-releases/snyk-win.exe
make binary-releases/snyk-linux-arm64

./docker-desktop/build.sh darwin x64
./docker-desktop/build.sh darwin arm64
./release-scripts/docker-desktop-release.sh

# compute checksums
pushd binary-releases
# note: checksum for docker-mac-signed-bundle is generated by `docker-desktop-release.sh`

ls -la
