name: 'Danger Zone'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [master, main, release-candidate]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          # registry-url triggers setup-node to create an .npmrc with auth token interpolation,
          # required to install private @snyk packages
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HAMMERHEAD_NPM_TOKEN }}
      - run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
